### ISSUE TITLE
matplotlib backend

### ISSUE THREAD

**Issue by usagliaschi** [bluenote10/PandasDataFrameGUI#3] opened 2016-07-25 12:06 UTC
Hi,

great project, really useful for exploring big dataset without printing DataFrames to excel. May I ask you to look into the following error?

In [1]: import dfgui
/usr/local/lib/python2.7/site-packages/matplotlib/**init**.py:1350: UserWarning:  This call to matplotlib.use() has no effect
because the backend has already been chosen;
matplotlib.use() must be called _before_ pylab, matplotlib.pyplot,
or matplotlib.backends is imported for the first time.

  warnings.warn(_use_error_msg)

It happens when I import the module on my ipython configuration which has osx as default matplotlib backend.

Many thanks,
Umberto

**Comment by bluenote10** [comment] 2016-07-25 18:03
As long as you are able to see the GUI there is nothing wrong about this warning. It happens in [this line](https://github.com/bluenote10/PandasDataFrameGUI/blob/master/dfgui/dfgui.py#L17) which is needed to make sure a GUI-capable backend is used. The problem is that your environment already has imported `matplotlib.pyplot` so the backend is already fixed. If you really want to get rid of the warning you would have to make sure that your environment does not import matplotlib in the startup (can be done in the IPython configuration files I guess). I may also be able to silent the warning, but this is not a good idea if a user already chosen the _wrong_ backend.

**Comment by opalbert** [comment] 2017-08-25 10:14
Hi bluenote10, I am getting the same warning but no error. Meanwhile I am not seeing the GUI. Thank you for this great project.

**Comment by bluenote10** [comment] 2017-08-25 14:40
@opalbert The problem must be the way you are launching the GUI. The problem is that a call like this 

```python
import matplotlib
matplotlib.use('WXAgg')
```

can only be made before any use of matplotlib functionality. If your code already contains calls to any matplotlib stuff, the backend is already determined and there is no way for `dfgui.show()` to change it anymore. Apparently in your case your initialization code picks a backend which is not compatible with wxpython. To solve the issue you either have to execute the two lines above at the very beginning of your code explicitly, or avoid other matplotlib usage which picks the wrong backend.

**Comment by bluenote10** [comment] 2017-08-30 12:23
Could you solve your issue? I'll close this issue, because there is probably nothing that can be done on the dfgui side.

**Closed by bluenote10** 2017-08-30 12:23 UTC

**Comment by CsatiZoltan** [comment] 2020-03-12 17:14
@bluenote10 You can enforce the `WXAgg` backend by changing https://github.com/bluenote10/PandasDataFrameGUI/blob/c4dcd6baa39deeb6f030f11ff6dc6a19a799b598/dfgui/dfgui.py#L17 to
```python
matplotlib.use('WXAgg', force=True)
```
